### ISSUE TITLE
feat/[edit] 관리 페이지 대시보드 삭제

### ISSUE THREAD

**Issue by KingNono1030** [team-second/taskify#108]
## 어떤 기능인가요?

> 대시보드 삭제 요청 관련된 작업

## 작업 상세 내용
저번에 이야기 나눈대로 삭제 버튼의 가시성을 높이던가, 버튼을 눌렀을 때 사용자를 좀 귀찮게 하는 안전장치가 있으면 좋을거 같습니다
like 깃헙 리포 삭제 (정말로 삭제하시겠습니까 모달)

- [ ] TODO
- [ ] TODO
- [ ] TODO

## 팀원들에게 알리고 싶다
- 
-  

## 참고할만한 자료(선택)
- 
-

**Comment by JuhyeokC** [comment]
https://github.com/team-second/taskify/pull/163/commits/d1687c2c21fda9c5b562d9ee7b2951fcfe2584e4

#163 에서 삭제 기능은 만들어두었습니다
