### ISSUE TITLE
refactor/[dashboard/id] 대시보드 페이지 칼럼 가로 스크롤 없애기

### ISSUE THREAD

**Issue by KingNono1030** [team-second/taskify#113]
## 어떤 기능인가요?

> 칼럼 하나당 가로 스크롤 있는거 보기 안좋아서, 안 나오게 레이아웃 재조정하면 좋을 것 같습니다!

![Image](https://github.com/user-attachments/assets/fe87b5e6-dfdd-4e48-9bd1-21cb6c6ced10)

## 작업 상세 내용

- [ ] TODO
- [ ] TODO
- [ ] TODO

## 팀원들에게 알리고 싶다
- 
-  

## 참고할만한 자료(선택)
- 
-

**Comment by JuhyeokC** [comment]
#122 에서 해결했습니다~

이슈 생성해두신 걸 확인못하고 새로 만들어서 작업했네요 ㅜ
