### ISSUE TITLE
fix/기본테마 다크 -> 라이트

### ISSUE THREAD

**Issue by KingNono1030** [team-second/taskify#124]
## 어떤 기능인가요?

> 

## 작업 상세 내용
<img width="1246" alt="image" src="https://github.com/user-attachments/assets/1f6c3f0f-6dbe-48a5-8fb2-d326206e1451">

- [ ] TODO
- [ ] TODO
- [ ] TODO

## 팀원들에게 알리고 싶다
- 
-  

## 참고할만한 자료(선택)
- 
-

**Comment by JuhyeokC** [comment]
글로벌 기본 테마 => light
랜딩페이지 테마 => dark

**Comment by ylem76** [comment]
일단 원인 먼저 확인했습니다.
next-theme라이브러리에서 사용자 테마 확인 후 알아서 body에 dark/light 클래스를 붙이는데요
페이지 넘어가도 body의 클래스는 삭제되지 않아서 그랬었네요
