### ISSUE TITLE
feat/레이아웃 컴포넌트

### ISSUE THREAD

**Issue by JuhyeokC** [team-second/taskify#20]
## 어떤 기능인가요?

> 헤더와 사이드바 레이아웃 컴포넌트 설계와 반응형 구현

## 작업 상세 내용

- [ ] 로고, 사이드바 반응형 구현
- [ ] 헤더, 사이드바 레이아웃 구조 수정

## 팀원들에게 알리고 싶다
- 레이아웃 폴더 구조에 대해 이해가 부족합니다. 이야기 나누고 싶습니다.
- 

## 참고할만한 자료(선택)
- https://nextjs.org/docs/app/api-reference/file-conventions/layout
- https://rocketengine.tistory.com/entry/NextJS-13-Routing-Pages-and-Layouts

**Comment by KingNono1030** [comment]
저도 이 부분 이야기 나누면 좋을거 같아요!!

해당 레이아웃은 여러 페이지가 공유하고 있어서 (mydashboard 랑 dashboard/{id}/edit 다른 폴더에 위치)
어디에 위치하는게 베스트일지 고민이 드네요

**Comment by JuhyeokC** [comment]
> 저도 이 부분 이야기 나누면 좋을거 같아요!!
> 
> 해당 레이아웃은 여러 페이지가 공유하고 있어서 (mydashboard 랑 dashboard/{id}/edit 다른 폴더에 위치) 어디에 위치하는게 베스트일지 고민이 드네요

좋습니다! 오늘 팀미팅 때 얘기나눠봐요!
