### ISSUE TITLE
feat/ dashboard/[id] 페이지 레이아웃

### ISSUE THREAD

**Issue by KingNono1030** [team-second/taskify#36]
## 어떤 기능인가요?

> #35 에서 완성한 칼럼들을 배열렌더링 하는 페이지의 레이아웃 작업
> 데스크탑일 때, 칼럼들이 좌 -> 우 방향으로 배치가 바뀝니다.

## 작업 상세 내용
![Image](https://github.com/user-attachments/assets/bf38de50-38b1-487d-993f-d145169711d0)
![Image](https://github.com/user-attachments/assets/fe03d944-d3b1-46f5-bfcf-8f558d2cf8b5)

- [ ]  TODO
- [ ]  TODO
- [ ]  TODO

## 팀원들에게 알리고 싶다

- 
- 

## 참고할만한 자료(선택)

- 
- 

> 이슈명은 제가 임의로 지은거니, 작업하시면서 편하게 바꾸세요~
>

**Comment by JuhyeokC** [comment]
소영님이 작업중이신 카드 컴포넌트 작업완료 이후 페어코딩 레츠고!
