### ISSUE TITLE
feat/라우터디렉토리 수정

### ISSUE THREAD

**Issue by JiinSeok** [team-second/taskify#43]
현재 앱 라우터 디렉토리가 카멜케이스로 되어 있어 링크를 카멜케이스로 해야 접속됩니다.
또한 로그인, 회원가입 페이지 분리가 이루어져 있지 않습니다.

위 사항 포함해서 피그마에 나와 있는대로 라우터 디렉토리 이름을 수정하려고 합니다.

**Comment by JuhyeokC** [comment]
제가 만들 때 버릇처럼 카멜케이스를 사용했네요

감사합니다!
