### ISSUE TITLE
feat/[레이아웃] 헤더 사용자 컴포넌트 개발

### ISSUE THREAD

**Issue by JuhyeokC** [team-second/taskify#96]
## 어떤 기능인가요?

> 헤더 우측의 사용자정보(프로필, 이름)를 표현하는 컴포넌트 입니다.

![Image](https://github.com/user-attachments/assets/fc872937-ff49-49a2-96bf-a8317883212a)
> 사용자정보

![Image](https://github.com/user-attachments/assets/bd8f7746-217b-4012-b7dd-fee456ff672a)
> 드롭다운

## 작업 상세 내용

- [x] 사용자 프로필
- [x] 사용자 이름
- [x] onClick -> 드롭다운(계정 관리, 로그아웃) 구현

## 팀원들에게 알리고 싶다
- 대시보드 멤버 컴포넌트에서 재사용될 수 있게 고려하면 좋을 것 같습니다
-  

## 참고할만한 자료(선택)
- 
-

**Comment by KingNono1030** [comment]
이거는 프로필 저 땡그란 부분만 컴포넌트로 만들고, 이름은 그냥 <span><Profile />정윤호</span> 이렇게 붙이는게 더 좋을거 같아요.
Profile 부분만 재사용 많이 되어서 그렇습니다
